// pkg/hostagent/host.proto

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.0
// source: pkg/hostagent/host.proto

package hostagent

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	HostAgent_ProvisionVM_FullMethodName = "/hostagent.HostAgent/ProvisionVM"
)

// HostAgentClient is the client API for HostAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HostAgentClient interface {
	ProvisionVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error)
}

type hostAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewHostAgentClient(cc grpc.ClientConnInterface) HostAgentClient {
	return &hostAgentClient{cc}
}

func (c *hostAgentClient) ProvisionVM(ctx context.Context, in *VMRequest, opts ...grpc.CallOption) (*VMResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VMResponse)
	err := c.cc.Invoke(ctx, HostAgent_ProvisionVM_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HostAgentServer is the server API for HostAgent service.
// All implementations must embed UnimplementedHostAgentServer
// for forward compatibility.
type HostAgentServer interface {
	ProvisionVM(context.Context, *VMRequest) (*VMResponse, error)
	mustEmbedUnimplementedHostAgentServer()
}

// UnimplementedHostAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedHostAgentServer struct{}

func (UnimplementedHostAgentServer) ProvisionVM(context.Context, *VMRequest) (*VMResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ProvisionVM not implemented")
}
func (UnimplementedHostAgentServer) mustEmbedUnimplementedHostAgentServer() {}
func (UnimplementedHostAgentServer) testEmbeddedByValue()                   {}

// UnsafeHostAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HostAgentServer will
// result in compilation errors.
type UnsafeHostAgentServer interface {
	mustEmbedUnimplementedHostAgentServer()
}

func RegisterHostAgentServer(s grpc.ServiceRegistrar, srv HostAgentServer) {
	// If the following call pancis, it indicates UnimplementedHostAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&HostAgent_ServiceDesc, srv)
}

func _HostAgent_ProvisionVM_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HostAgentServer).ProvisionVM(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HostAgent_ProvisionVM_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HostAgentServer).ProvisionVM(ctx, req.(*VMRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HostAgent_ServiceDesc is the grpc.ServiceDesc for HostAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HostAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "hostagent.HostAgent",
	HandlerType: (*HostAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ProvisionVM",
			Handler:    _HostAgent_ProvisionVM_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/hostagent/host.proto",
}
