// pkg/hostagent/host.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.31.0
// source: pkg/hostagent/host.proto

package hostagent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VMRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Cores         int32                  `protobuf:"varint,2,opt,name=cores,proto3" json:"cores,omitempty"`
	Memory        int32                  `protobuf:"varint,3,opt,name=memory,proto3" json:"memory,omitempty"`
	Disk          int32                  `protobuf:"varint,4,opt,name=disk,proto3" json:"disk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMRequest) Reset() {
	*x = VMRequest{}
	mi := &file_pkg_hostagent_host_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMRequest) ProtoMessage() {}

func (x *VMRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hostagent_host_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMRequest.ProtoReflect.Descriptor instead.
func (*VMRequest) Descriptor() ([]byte, []int) {
	return file_pkg_hostagent_host_proto_rawDescGZIP(), []int{0}
}

func (x *VMRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VMRequest) GetCores() int32 {
	if x != nil {
		return x.Cores
	}
	return 0
}

func (x *VMRequest) GetMemory() int32 {
	if x != nil {
		return x.Memory
	}
	return 0
}

func (x *VMRequest) GetDisk() int32 {
	if x != nil {
		return x.Disk
	}
	return 0
}

type VMResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	VmId          string                 `protobuf:"bytes,2,opt,name=vm_id,json=vmId,proto3" json:"vm_id,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VMResponse) Reset() {
	*x = VMResponse{}
	mi := &file_pkg_hostagent_host_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VMResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VMResponse) ProtoMessage() {}

func (x *VMResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_hostagent_host_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VMResponse.ProtoReflect.Descriptor instead.
func (*VMResponse) Descriptor() ([]byte, []int) {
	return file_pkg_hostagent_host_proto_rawDescGZIP(), []int{1}
}

func (x *VMResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VMResponse) GetVmId() string {
	if x != nil {
		return x.VmId
	}
	return ""
}

func (x *VMResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_pkg_hostagent_host_proto protoreflect.FileDescriptor

const file_pkg_hostagent_host_proto_rawDesc = "" +
	"\n" +
	"\x18pkg/hostagent/host.proto\x12\thostagent\"f\n" +
	"\tVMRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05cores\x18\x02 \x01(\x05R\x05cores\x12\x16\n" +
	"\x06memory\x18\x03 \x01(\x05R\x06memory\x12\x12\n" +
	"\x04disk\x18\x04 \x01(\x05R\x04disk\"Q\n" +
	"\n" +
	"VMResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x13\n" +
	"\x05vm_id\x18\x02 \x01(\tR\x04vmId\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error2G\n" +
	"\tHostAgent\x12:\n" +
	"\vProvisionVM\x12\x14.hostagent.VMRequest\x1a\x15.hostagent.VMResponseB\x1fZ\x1dinfra-scheduler/pkg/hostagentb\x06proto3"

var (
	file_pkg_hostagent_host_proto_rawDescOnce sync.Once
	file_pkg_hostagent_host_proto_rawDescData []byte
)

func file_pkg_hostagent_host_proto_rawDescGZIP() []byte {
	file_pkg_hostagent_host_proto_rawDescOnce.Do(func() {
		file_pkg_hostagent_host_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_hostagent_host_proto_rawDesc), len(file_pkg_hostagent_host_proto_rawDesc)))
	})
	return file_pkg_hostagent_host_proto_rawDescData
}

var file_pkg_hostagent_host_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_hostagent_host_proto_goTypes = []any{
	(*VMRequest)(nil),  // 0: hostagent.VMRequest
	(*VMResponse)(nil), // 1: hostagent.VMResponse
}
var file_pkg_hostagent_host_proto_depIdxs = []int32{
	0, // 0: hostagent.HostAgent.ProvisionVM:input_type -> hostagent.VMRequest
	1, // 1: hostagent.HostAgent.ProvisionVM:output_type -> hostagent.VMResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_hostagent_host_proto_init() }
func file_pkg_hostagent_host_proto_init() {
	if File_pkg_hostagent_host_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_hostagent_host_proto_rawDesc), len(file_pkg_hostagent_host_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_hostagent_host_proto_goTypes,
		DependencyIndexes: file_pkg_hostagent_host_proto_depIdxs,
		MessageInfos:      file_pkg_hostagent_host_proto_msgTypes,
	}.Build()
	File_pkg_hostagent_host_proto = out.File
	file_pkg_hostagent_host_proto_goTypes = nil
	file_pkg_hostagent_host_proto_depIdxs = nil
}
